export const CONTACT_ACTIONS = {
  SET_CONTACTS: 'CONTACT_ACTIONS/SET_CONTACTS',
  GET_CONTACTS_SUCCESS: 'CONTACT_ACTIONS/GET_CONTACTS_SUCCESS',
  GET_CONTACTS_ERROR: 'CONTACT_ACTIONS/GET_CONTACTS_ERROR'
};
