export const MAIL_ACTIONS = {
  SET_MAILS: 'MAIL_ACTIONS/SET_MAILS',
  GET_MAILS_SUCCESS: 'MAIL_ACTIONS/GET_MAILS_SUCCESS',
  GET_MAILS_ERROR: 'MAIL_ACTIONS/GET_MAILS_ERROR',
  GET_MAIL_SUCCESS: 'MAIL_ACTIONS/GET_MAIL_SUCCESS',
};
